version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "9090:9090"
    environment:
      - HOME_URL=http://localhost:9090
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - FIRECRAWL_API_URL=${FIRECRAWL_API_URL}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - LAMB_API_KEY=0p3n-w3bu!
      - EMBEDDINGS_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - EMBEDDINGS_VENDOR=ollama
      - EMBEDDINGS_API_ENDPOINT=http://127.0.0.1:11434
    volumes:
      - ./backend:/app/backend
      - ./static:/app/static
      - kb-data:/app/data
    network_mode: "host"
    extra_hosts:
    - "host.docker.internal:host-gateway"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://127.0.0.1:9090
      - API_TOKEN=0p3n-w3bu!
    depends_on:
      - backend
    network_mode: "host"
    extra_hosts:
    - "host.docker.internal:host-gateway"

volumes:
  kb-data:
    name: lamb-kb-data
  static-files:
    name: lamb-static-files